### ISSUE TITLE
TypeError: Cannot destructure property `vulnerabilities` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by RobCoPKC** [acac99/npm-audit-pipeline#32]
Hey,

I'm getting a weird error when running "npm run package-audit". The behavior isn't consistent and it seems to happen at random:

C:\Data\workspaces\my-app>npm run package-audit

> my-app@0.0.0 package-audit C:\Data\workspaces\my-app
> npm-audit

C:\Data\workspaces\my-app\node_modules\npm-audit-pipeline\NpmAuditParser.js:21
      metadata: { vulnerabilities }
                  ^

TypeError: Cannot destructure property `vulnerabilities` of 'undefined' or 'null'.
    at Object.getVulnerabilities (C:\Data\workspaces\my-app\node_modules\npm-audit-pipeline\NpmAuditParser.js:21:17)
    at Object.runAudit (C:\Data\workspaces\my-app\node_modules\npm-audit-pipeline\NpmAuditor.js:24:44)
    at C:\Data\workspaces\my-app\node_modules\npm-audit-pipeline\index.js:21:56
    at ChildProcess.exithandler (child_process.js:302:5)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-app@0.0.0 package-audit: `npm-audit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-app@0.0.0 package-audit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <logpath>

C:\Data\workspaces\my-app>npm run package-audit

> my-app@0.0.0 package-audit C:\Data\workspaces\my-app
> npm-audit

NPM audit passed...

I didn't change any code between the 2 runs...
Any ideas?

Kind regards,
Robin

**Comment by RobCoPKC** [comment]
I can't reproduce this for the life of me. No idea what kind of stars aligned for me to encounter this error > 20 times.
Closing this issue now.

**Comment by acac99** [comment]
Hey sorry didn't see your post. Thanks for bringing this up. I believe that issue sometimes happens when it tries to fetch for the vulnerabilities and NPM fails to return a response hence causing the crash. I will update it later tonight with some retry logic and a more meaningful error if it does failed to fetch from NPM

**Comment by acac99** [comment]
Okay I've publish the updated changes to 0.4.0 which you can pull whenever. with retrying logic and logging of the error returned from NPM audit. 
It now has retry logic when fetching npm audit (defaults to 3 attempts) and now logs out the error from npm audit if it fails after those 3 attempts. I also updated the README with a couple of additional flag options you can use if needed. If you want to simulate the error situation, disconnect from the internet and then run `npm run package-audit` as from the README and you should see the error response logged out. 
I'm gonna close out this issue since it's now properly fixed
